mod.name=LegacyEntityGlow
mod.description=Backports 1.9+'s entity glowing effect to 1.8.9
mod.id=legacyentityglow
mod.group=dev.cxntered
mod.version=1.1.0
mod.mc_version=1.8.9

publish.modrinth.id=NdHtWIqW
publish.github.repo=cxntered/LegacyEntityGlow
publish.github.branch=main

org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true
